### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by ddespr50** [Rdelia11/First-Project-Web#3]
**création navbar avec :**
- home
- logo decathlon
- logo panier
- login

**Deux états :** 
- invité 
- connecté

**Comment by NicoPrv** [comment]
<img width="1404" alt="capture d ecran 2018-06-11 a 17 16 47" src="https://user-images.githubusercontent.com/38031265/41240650-55ffa576-6d9b-11e8-9d63-9b55f51c3358.png">
done!
